name: GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      # src フォルダの中身を artifact としてアップロードする
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'src'  # ここで src を指定するのがポイントです

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4